D = {
 'industries/pharmaceutical': ('Pharma & Life Sciences SEO and AI Search | Reinforce Lab', 'Search, content and AI visibility for pharma and life sciences companies, built around medical-legal review, evidence and the rules on promoting medicines.'),
 'services/agents/evidence-verification': ('Evidence Verification AI Agent | Reinforce Lab', 'The Evidence Verification Agent ties every important claim in your content to a source, scores confidence and flags weak evidence for a person to review.'),
 'services/agents/aeo-geo-optimization': ('AEO / GEO Optimization AI Agent | Reinforce Lab', None),
 'services/agents/competitor-intelligence': ('Competitor Intelligence AI Agent | Reinforce Lab', None),
 'services/agents/search-performance': ('Search Performance AI Agent | Reinforce Lab', None),
 'services/agents/social-sentiment': (None, 'The Social Sentiment Agent turns real customer questions, objections and complaints from forums, reviews and social posts into topics, angles and FAQs.'),
 'services/seo-content-systems': ('SEO Content Writing Services & Systems | Reinforce Lab', 'SEO content writing run as a system: research, topic maps, expert-led briefs, human-edited pages, internal links and refreshes that rank and get cited.'),
 'services/marketing-automation': ('Marketing Automation & Email Services | Reinforce Lab', 'Marketing automation that follows up every lead: nurture emails, lead scoring, CRM workflows and sales handoff, within Gmail, CAN-SPAM and PECR rules.'),
 'services/lead-generation-systems': ('B2B Lead Generation & PPC Services | Reinforce Lab', 'Lead generation systems that turn demand into qualified pipeline: PPC, landing pages, lead qualification and CRM data that shows which leads became revenue.'),
 'services/generative-engine-optimization': (None, 'Generative Engine Optimization (GEO) from Reinforce Lab: pages structured, sourced and written so ChatGPT, Perplexity and AI Overviews quote and cite you.'),
 'services/seo-ai-search-audit': (None, 'A one-time, human-led audit of your technical SEO, content, authority, competitors and AI search visibility, with a prioritised fix register and roadmap.'),
 'industries/healthcare': (None, 'Healthcare SEO and AI search for clinics and providers: local visibility, clinician-reviewed content, accurate AI answers and privacy-aware websites.'),
 'services/ai-workflow-automation': (None, 'AI workflow automation for triage, document extraction, drafting and system updates, with human review and logging: AI does the busywork, people keep control.'),
 'services/enterprise-seo-strategy': (None, 'Enterprise SEO strategy for large sites: one SEO standard across teams, template fixes shipped in your sprints, safe migrations and authority you earn.'),
 'services/technical-seo-services': (None, 'Technical SEO: crawlability, indexation, Core Web Vitals, structured data and AI-crawler access, with root causes fixed and verified, safe for what ranks.'),
 'services/llm-optimization': (None, 'LLM Optimization: make ChatGPT, Claude, Gemini and Perplexity describe your brand correctly, with consistent facts, the right crawler policy and tested answers.'),
 'services/executive-ai-consulting': (None, 'Executive AI consulting for leadership teams: prioritised use cases, business cases, governance, EU AI Act mapping and a roadmap through the first pilots.'),
 'services/local-seo': (None, "Local SEO from Reinforce Lab: Google Business Profile, consistent citations, compliant reviews and location pages, built on Google's local search guidelines."),
 'services/press-release-services': (None, "Digital PR and link building that earns coverage, links and AI citations: original data and expert commentary, no bought links, within Google's policies."),
 'services/best-search-engine-optimization-services': (None, "SEO services built on Google's guidelines: technical SEO, on-page, content and authority run as one system and extended to AI search for B2B brands."),
 'services/wordpress-website-design-service': (None, 'WordPress website design for B2B brands: custom design, editor-friendly builds, fast Core Web Vitals, WCAG 2.2 AA accessibility and rankings kept safe.'),
 'services/ecommerce-website-design-service': (None, 'E-commerce website design on WooCommerce: product data for Google, easy browsing, a shorter checkout, fast pages and WCAG 2.2 AA accessibility.'),
 'services/website-maintenance-services': (None, 'Website maintenance for WordPress: tested updates, off-site backups, security and uptime monitoring, speed and SEO checks, support and a monthly report.'),
}
