#!/usr/bin/env python3
"""Writes claude/site-map.md: every page on reinforcelab.online with its ID, status, URL and the
theme file that renders it. Offline: reads claude/data/online-snapshot/pages.json (refresh it first
with `rl.py snapshot`) and the add_shortcode() calls in wp/novamira-sandbox/.

    python3 claude/tools/site-map.py
"""
import json, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SANDBOX = ROOT / 'wp/novamira-sandbox'
SNAP = ROOT / 'claude/data/online-snapshot/pages.json'
OUT = ROOT / 'claude/site-map.md'
SITE = 'https://reinforcelab.online'

# Pages rendered by a template_redirect template rather than a shortcode.
TEMPLATES = {'/blog/': 'blog/reinforce-blog.php'}

shortcodes = {}
for f in sorted(SANDBOX.rglob('*.php')):
    if '_backups' in f.parts:
        continue
    for tag in re.findall(r"add_shortcode\(\s*'([\w-]+)'", f.read_text(encoding='utf-8')):
        shortcodes[tag] = f.relative_to(SANDBOX).as_posix()

pages = json.load(open(SNAP, encoding='utf-8'))


def group(path):
    if path == '/':
        return 'Home'
    if path.startswith('/services/agents/'):
        return 'Agents'
    for prefix, name in (('/services/', 'Services'), ('/industries/', 'Industries'), ('/blog/', 'Blog')):
        if path.startswith(prefix):
            return name
    if path in ('/search-authority-os/', '/search-authority-diagnostic/', '/packages/'):
        return 'Search Authority OS'
    if path.startswith('/?'):
        return 'Drafts'
    return 'Company'


def link(rel):
    return f'[`{rel}`](../wp/novamira-sandbox/{rel})'


ORDER = ['Home', 'Company', 'Services', 'Industries', 'Search Authority OS', 'Agents', 'Blog', 'Drafts']
rows = {g: [] for g in ORDER}
for p in pages:
    if p['type'] != 'page':
        continue
    tags = re.findall(r'\[(reinforce_\w+)', p['content'] or '')
    files = sorted({shortcodes[t] for t in tags if t in shortcodes} - {'core/reinforce-header.php'})
    if p['path'] in TEMPLATES:
        files = [TEMPLATES[p['path']]]
    seo = p['seo'] if isinstance(p['seo'], dict) else {}
    title = (seo.get('_yoast_wpseo_title') or '').replace('|', '\\|')
    url = p['path'] if p['status'] != 'publish' else f"[{p['path']}]({SITE}{p['path']})"
    rows[group(p['path'])].append(
        f"| {p['id']} | {p['title'].replace('|', '/')} | {url} | {p['status']} | "
        f"{', '.join(link(f) for f in files) or 'WordPress editor'} | {title} |")

lines = [
    '# Site map: reinforcelab.online',
    '',
    'Every page on the development site, the page ID in WordPress, and the theme file that renders it.',
    'Generated by `python3 claude/tools/site-map.py` from the last `rl.py snapshot`. Do not edit by hand.',
    '',
    'Header and footer on every page: [`core/reinforce-header.php`](../wp/novamira-sandbox/core/reinforce-header.php).',
    'Shared styles: [`core/reinforce-kit.css`](../wp/novamira-sandbox/core/reinforce-kit.css).',
    'Single blog posts: [`blog/reinforce-post.php`](../wp/novamira-sandbox/blog/reinforce-post.php) '
    '(all types), [`blog/reinforce-post-types.php`](../wp/novamira-sandbox/blog/reinforce-post-types.php) '
    '(per-type fields), [`blog/reinforce-post-guide.php`](../wp/novamira-sandbox/blog/reinforce-post-guide.php) (Guide), '
    '[`blog/reinforce-post-howto.php`](../wp/novamira-sandbox/blog/reinforce-post-howto.php) (How-To), '
    '[`blog/reinforce-post-list.php`](../wp/novamira-sandbox/blog/reinforce-post-list.php) (Best / List), '
    '[`blog/reinforce-post-review.php`](../wp/novamira-sandbox/blog/reinforce-post-review.php) (Review).',
    '',
]
for g in ORDER:
    if not rows[g]:
        continue
    lines += [f'## {g} ({len(rows[g])})', '', '| ID | Page | URL | Status | Renders from | SEO title |',
              '|---|---|---|---|---|---|', *rows[g], '']

OUT.write_text('\n'.join(lines), encoding='utf-8')
print(f'wrote {OUT.relative_to(ROOT)}: {sum(len(r) for r in rows.values())} pages')
